### ISSUE TITLE
Apex unable to resolve dependencies betwen MapboxVision and MapboxVisionAR v0.13.0 using CocoaPods

### ISSUE THREAD

**Issue by avi-c** [mapbox/mapbox-vision-ios#339]
## Description
Recently and without changes to Apex Cocoapods has become unable to get a working copy of the Vision 0.13.0 frameworks when using both MapboxVision and MapboxVisionAR.

## Expected behavior
- Clone https://github.com/mapbox/apex repo
- Follow steps to build app.
- CocoaPods finishes correctly and then you can open the Xcode project and run the app

## Actual behavior
Cocoapods errors out with this message:

[!] CocoaPods could not find compatible versions for pod "MapboxVision":
  In Podfile:
    MapboxVision (from `https://github.com/mapbox/mapbox-vision-ios.git`, branch `vision-0.13-telemetry-0.10.2`)

    MapboxVisionAR (from `https://github.com/mapbox/mapbox-vision-ios.git`, branch `release/0.13.0`) was resolved to 0.13.0, which depends on
      MapboxVision (= 0.13.0)

## Configuration
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS13]
 - Frameworks versions (leave the ones you're using):
   - MapboxVisionNative [e.g. 0.13.0]
   - MapboxVisionARNative [e.g. 0.13.0]
   - MapboxVision [e.g. 0.13.0]
   - MapboxVisionAR [e.g. 0.13.0]

## Additional context
Was working until recently and Apex hasn't changed

**Comment by avi-c** [comment]
Only workaround for this is to disable and remove Vision from Apex.

**Comment by chezzdev** [comment]
@dersim-davaod could you please unwind your changes from `vision-0.13-telemetry-0.10.2` branch and push them to another one so that Apex is unblocked?

**Comment by dersim-davaod** [comment]
done, `vision-0.13-telemetry-0.10.2` contains MME of v0.10.2 now.

**Comment by chezzdev** [comment]
Thanks, @dersim-davaod.
@avi-c please confirm that the branch works for you again.

**Comment by avi-c** [comment]
Still having issues. On a fresh checkout and `pod install` I see this error from CocoaPods:

Pre-downloading: `MapboxVision` from `https://github.com/mapbox/mapbox-vision-ios.git`, commit `ebfb7a7a13c247798cf1de202c4f3182d7dd9427`

[!] Error installing MapboxVision
[!] Failed to download 'MapboxVision': [!] /usr/local/bin/git -C /var/folders/b9/_glfh3h90x3f8h65fffdb1fr0000gn/T/d20201023-4538-17z5ltk checkout --quiet ebfb7a7a13c247798cf1de202c4f3182d7dd9427

fatal: reference is not a tree: ebfb7a7a13c247798cf1de202c4f3182d7dd9427

**Comment by avi-c** [comment]
And that is with the same podfile entries as have been there (working) for a few months:

pod 'MapboxVisionNativeAll', :podspec => 'https://api.mapbox.com/downloads/v1/vision/ios/mapbox-vision-native-all/0.13.0.podspec?access_token=sk.eyJ1IjoiYXRyaXBhdGhpLW1iIiwiYSI6ImNqdWs3bmM5YjBqNm4zeW80Y25seDRmdXAifQ.Ki2-OqL-MULdVi2Q4jacSA'
    # Vision only
    pod "MapboxVision", :git => 'https://github.com/mapbox/mapbox-vision-ios.git', :branch => 'vision-0.13-telemetry-0.10.2'
    # AR
    pod "MapboxVisionAR", :git => 'https://github.com/mapbox/mapbox-vision-ios.git', :branch => 'release/0.13.0'

**Comment by avi-c** [comment]
Also, I get this error if I try a `pod update`:

[!] CocoaPods could not find compatible versions for pod "MapboxVision":
  In Podfile:
    MapboxVision (from `https://github.com/mapbox/mapbox-vision-ios.git`, branch `vision-0.13-telemetry-0.10.2`)

    MapboxVisionAR (from `https://github.com/mapbox/mapbox-vision-ios.git`, branch `release/0.13.0`) was resolved to 0.13.0, which depends on
      MapboxVision (= 0.13.0)

**Comment by avi-c** [comment]
@chezzdev created a new branch for Apex to pull from and this seems to be working again.

pod 'MapboxVisionNativeAll', :podspec => 'https://api.mapbox.com/downloads/v1/vision/ios/mapbox-vision-native-all/0.13.1.podspec?access_token='
pod "MapboxVision", :git => 'https://github.com/mapbox/mapbox-vision-ios.git', :tag => 'vision-0.13.1-telemetry-0.10.2'
pod "MapboxVisionAR", :git => 'https://github.com/mapbox/mapbox-vision-ios.git', :tag => 'v0.13.1'
pod "MapboxVisionSafety", :git => 'https://github.com/mapbox/mapbox-vision-ios.git', :tag => 'v0.13.1'
